---
#-
#  _ _       _     _
# | (_) __ _| |__ | |_ ___
# | | |/ _` | '_ \| __/ __|
# | | | (_| | | | | |_\__ \
# |_|_|\__, |_| |_|\__|___/
#      |___/
#
#- from github.com/basnijholt/home-assistant-config
- platform: group
  name: Living room lights
  entities:
    - light.sphere
    - light.corner_living_room
    - light.tv_led
    - light.cabinet_led

- platform: group
  name: Bedroom lights
  entities:
    - light.philips_go
    - light.ceiling_bedroom
    - light.bed_led
    - light.bamboo
    # - light.lampan
    # - light.bed_reading_up
    # - light.bed_reading_down

- platform: group
  name: Bedroom lights Hue
  entities:
    - light.philips_go
    - light.bed_led
    - light.bamboo
    # - light.lampan
    # - light.bed_reading_up
    # - light.bed_reading_down

- platform: group
  name: Automatic lights
  entities:
    - light.ceiling_kitchen
    - light.bathroom_ceiling
    - light.bathroom_mirror
    # - light.kitchen_counter
    # - light.hall_lights

- platform: group
  name: Kitchen lights
  entities:
    - light.ceiling_kitchen
    # - light.kitchen_counter

- platform: switch
  name: Kitchen counter
  entity_id: switch.kitchen_counter

- platform: group
  name: Bathroom lights
  entities:
    - light.bathroom_ceiling
    - light.bathroom_mirror

# - platform: group
#   name: Hall lights
#   entities:
#     - light.hall_1
#     - light.hall_2
#     - light.hall_3

- platform: group
  name: Bed reading
  entities:
    - light.bed_reading_up
    - light.bed_reading_down
